module.exports = {
  module: "google-material",
  node: 1,
  //   level 2
  children: [
    {
      module: "inputs",
      title: "Inputs",
      src: "/media/svg/icons/Design/PenAndRuller.svg",
      collapsed: true,
      node: 2,
      //   Level 3
      children: [
        { module: "autocomplete", title: "Autocomplete", node: 3 },
        { module: "buttons", title: "Buttons", node: 3 },
        { module: "checkboxes", title: "Checkboxes", node: 3 },
        { module: "pickers", title: "Pickers", node: 3 },
        { module: "radio-buttons", title: "Radio Buttons", node: 3 },
        { module: "selects", title: "Selects", node: 3 },
        { module: "switches", title: "Switches", node: 3 },
        { module: "text-fields", title: "Text Fields", node: 3 },
        { module: "transfer-list", title: "Transfer List", node: 3 },
      ],
    },
    {
      module: "navigation",
      node: 2,
      title: "Navigation",
      src: "/media/svg/icons/Navigation/Arrow-from-left.svg",
      collapsed: true,
      children: [
        { module: "bottom-navigation", title: "Bottom Navigation", node: 3 },
        { module: "breadcrumbs", title: "Breadcrumbs", node: 3 },
        { module: "drawer", title: "Drawers", node: 3 },
        { module: "links", title: "NavLinks", node: 3 },
        { module: "menus", title: "Menus", node: 3 },
        { module: "steppers", title: "Steppers", node: 3 },
        { module: "tabs", title: "Tabs", node: 3 },
      ],
    },
    {
      module: "surfaces",
      node: 2,
      title: "Surfaces",
      src: "/media/svg/icons/Layout/Layout-left-panel-1.svg",
      collapsed: true,
      children: [
        { module: "app-bar", title: "App Bar", node: 3 },
        { module: "paper", title: "Cards", node: 3 },
        { module: "cards", title: "Drawers", node: 3 },
        { module: "expansion-panels", title: "Expansion Panels", node: 3 },
      ],
    },
    {
      module: "feedback",
      node: 2,
      title: "Feedback",
      src: "/media/svg/icons/General/Half-star.svg",
      collapsed: true,
      children: [
        { module: "progress", title: "Progress", node: 3 },
        { module: "dialogs", title: "Dialogs", node: 3 },
        { module: "snackbars", title: "Snackbars", node: 3 },
      ],
    },
    {
      module: "data-displays",
      node: 2,
      title: "Data Display",
      src: "/media/svg/icons/Devices/iMac.svg",
      collapsed: true,
      children: [
        { module: "progress", title: "Progress", node: 3 },
        { module: "avatars", title: "Avatars", node: 3 },
        { module: "badges", title: "Badges", node: 3 },
        { module: "chips", title: "Chips", node: 3 },
        { module: "dividers", title: "Dividers", node: 3 },
        { module: "icons", title: "Icons", node: 3 },
        { module: "lists", title: "Lists", node: 3 },
        { module: "tables", title: "Tables", node: 3 },
        { module: "tooltips", title: "Tooltips", node: 3 },
        { module: "typography", title: "Typography", node: 3 },
      ],
    },
    {
      module: "utils",
      node: 2,
      title: "Utils",
      src: "/media/svg/icons/Tools/Swiss-knife.svg",
      collapsed: true,
      children: [
        {
          module: "click-away-listener",
          title: "Click Away Listener",
          node: 3,
        },
        { module: "modal", title: "Modal", node: 3 },
        { module: "no-ssr", title: "No SSR", node: 3 },
        { module: "popover", title: "Popover", node: 3 },
        { module: "portal", title: "Portal", node: 3 },
        { module: "transitions", title: "Transitions", node: 3 },
        { module: "use-media-query", title: "useMediaQuery", node: 3 },
        { module: "tables", title: "Tables", node: 3 },
        { module: "tooltips", title: "Tooltips", node: 3 },
        { module: "typography", title: "Typography", node: 3 },
      ],
    },
    {
      module: "layout",
      node: 2,
      title: "Layout",
      src: "/media/svg/icons/Layout/Layout-top-panel-2.svg",
      collapsed: true,
      children: [
        {
          module: "box",
          title: "Box",
          node: 3,
        },
        { module: "container", title: "Container", node: 3 },
        { module: "grid", title: "Grid", node: 3 },
        { module: "grid-list", title: "Grid list", node: 3 },
        { module: "hidden", title: "Hidden", node: 3 },
        { module: "transitions", title: "Transitions", node: 3 },
        { module: "use-media-query", title: "useMediaQuery", node: 3 },
        { module: "tables", title: "Tables", node: 3 },
        { module: "tooltips", title: "Tooltips", node: 3 },
        { module: "typography", title: "Typography", node: 3 },
      ],
    },
  ],
};
